<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerABuIMTe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerABuIMTe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerABuIMTe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerABuIMTe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerABuIMTe\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'ABuIMTe',
    'container.build_id' => 'cec8ea00',
    'container.build_time' => 1547482870,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerABuIMTe');
