<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHHYtA64\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHHYtA64/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHHYtA64.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHHYtA64\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHHYtA64\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'HHYtA64',
    'container.build_id' => '2cf6e988',
    'container.build_time' => 1547554132,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHHYtA64');
